services:
  db:
    image: my-mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - nextcloud

  redis:
    image: my-redis
    restart: always
    volumes:
      - ./redis_data:/data
    networks:
      - nextcloud

  nextcloud:
    image: my-nextcloud
    restart: always
    ports:
      - 8010:80
    environment:
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
      REDIS_HOST: redis
    volumes:
      - ./nextcloud_data:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - nextcloud

volumes:
  db_data:
  redis_data:
  nextcloud_data:

networks:
  nextcloud:
    external: true
    name: nextcloud
